# Generated by Django 4.2.13 on 2024-10-14 17:24

from django.db import migrations
import product.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_is_active_alter_productline_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productline',
            name='order',
            field=product.fields.OrderField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
